apiVersion: v1
kind: Service
metadata:
  name: mysharpapp-service
  namespace: dev
spec:
  type: NodePort
  selector:
    app: mysharpapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodeport: 8888
